### ISSUE TITLE
Publish a release with a wheel

### ISSUE THREAD

**Issue by Cadair** [asdf-format/asdf-coordinates-schemas#21]
Does your CI config as written support building pure Python wheels? It would be a nice improvement to ship a wheel.

**Comment by WilliamJamieson** [comment]
Yes the publish to PyPi action supports this. However, this particular package has not been released since we added that action.

**Comment by Cadair** [comment]
bug fix release time? :wink:

**Comment by WilliamJamieson** [comment]
Sure, do you need this soon?

**Comment by Cadair** [comment]
It's not that urgent really, I was just working through build issues on py 3.11 and noticed that this didn't have a wheel.

**Comment by WilliamJamieson** [comment]
@Cadair, `asdf-coordinates-schemas 0.2.0` now has a wheel: https://pypi.org/project/asdf-coordinates-schemas/#files, so I am closing this issue. If you have any problems please open a new one.
